name: owner-approval
on:
  pull_request:
  workflow_dispatch:

jobs:
  status:
    permissions:
      statuses: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check owner approval
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request ? context.payload.pull_request.number : '';
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'failure', // or 'failure', 'pending'
              context: 'Team owner approval',
              description: 'an approval from one of team owners is required',
              target_url: prNumber
                ? `https://github.com/${context.repo.owner}/${context.repo.repo}/pull/${prNumber}`
                : ''
            })
      # - name: Add reviewer
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.pulls.requestReviewers({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         pull_number: context.issue.number,
      #         reviewers: ['sfc-gh-mwalas'] // You can make this dynamic
      #       })