name: status-check
on:
  pull_request:
  workflow_dispatch:

jobs:
  status:
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Set status check
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request ? context.payload.pull_request.number : '';
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success', // or 'failure', 'pending'
              context: 'Dynamic Reviewer Check',
              description: 'All required reviewers have approved',
              target_url: prNumber
                ? `https://github.com/${context.repo.owner}/${context.repo.repo}/pull/${prNumber}`
                : ''
            })
      - name: Add reviewer
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ['sfc-gh-mwalas'] // You can make this dynamic
            })